// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nlpytrvdrkoiozjrjrqh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5scHl0cnZkcmtvaW96anJqcnFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5OTQ5MjYsImV4cCI6MjA2NjU3MDkyNn0.VvjqQDq-2U1MQJ7wLcBt0JfxDsOSJbY5T1MXILWW5Wk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);